language:
  - cpp
sudo: required
dist: trusty
cache: apt
env:
  global:
    - GCC_VERSION=7
    - LIBSTDC_VERSION=7

addons:
  apt:
    sources:
      - ubuntu-toolchain-r/test/ubuntu
      - llvm-toolchain-trusty
      - jonathonf/gcc-7.1/ubuntu
    packages:
      - clang-5.0
      - build-essential
      - binutils
#       - libboost-all-dev
      - cmake
      - libgtest-dev

before_install :
  - sudo add-apt-repository --yes ppa:jonathonf/binutils
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install gcc-7 g++-7
  - sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -

script:
  - clang++-5.0 --version
  - g++-7 --version
  - g++-7 -std=gnu++1z -Wall -Wextra -pedantic ProcessDumper/main.cpp && ./a.out
  - clang++-5.0 -std=gnu++1z -Wall -Wextra -pedantic ProcessDumper/main.cpp && ./a.out
